import numpy as np
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')

potts = np.load('r20_MSATF6K.npy')
potts1 = np.nanmean(potts, axis = 1)
msa = np.load('r20_MSATUF6K.npy')
msa1 = np.nanmean(msa, axis = 1)
ref = np.load('r20_ref.npy')
ref1 = np.nanmean(ref, axis = 1)
indep = np.load('r20_indep.npy')
indep1 = np.nanmean(indep, axis = 1)
p = np.load('r20_Potts.npy')
p1 = np.nanmean(p, axis = 1)
plt.figure(figsize=(4,4))
plt.plot(range(2,9), potts1, '.-', label='Filtered MSA-T', color='tab:orange', zorder=100)
plt.plot(range(2,9), msa1, '.-', label='Unfiltered MSA-T', color='tab:orange')
plt.plot(range(2,9), p1, '.--', label='Filtered Potts', color='tab:blue')
plt.plot(range(2,9), indep1, '.-', label='Filtered Indep', color='tab:grey')
plt.plot(range(2,9), ref1, '.-', label='Null Model', color='tab:green')
plt.ylim(0,1.05)
#plt.ylabel('r20')
#plt.xlabel('Higher Order Marginals')
#plt.title('')
plt.ylabel('r20', fontsize = 13)
plt.xlabel('Pattern Length', fontsize = 13)
plt.legend(loc='upper right', fontsize=9)
plt.xticks(ticks=[2, 4, 6, 8])
plt.yticks(ticks=[0.0, 0.5, 1.0])
plt.tight_layout(pad=1.2)
plt.savefig('fil_unfil.png')
#plt.legend(loc='upper right', fontsize=9)
plt.show()
